---
output: github_document
---

** UNDER CONSTRUCTION **

## The ONTOX Project

[ONTOX](ONTOX will deliver a generic strategy to create innovative new approach methodologies (NAMs) in order to predict systemic repeated dose toxicity effects that, upon combination with tailored exposure assessment, will enable human risk assessment.
This strategy can be applied to any type of chemical and systemic repeated dose toxicity effect. ) will deliver a generic strategy to create innovative new approach methodologies (NAMs) in order to predict systemic repeated dose toxicity effects that, upon combination with tailored exposure assessment, will enable human risk assessment.
This strategy can be applied to any type of chemical and systemic repeated dose toxicity effect. 

## Tools, Software and models
We envision to share the tools, software and models developed in ONTOX here. Stay tuned to these pages for updates. These Github pages will also be used to share the [documentation](/docs/docs.html).

## Links

 - [ontox-hu](https://github.com/ontox-hu)
 - [ontox.eu](https://ontox-project.eu/)
 - [codis.europa.eu](https://cordis.europa.eu/project/id/963845)

## Documentation
See [docs](/docs/docs.html)
